# Generated by Django 3.0.8 on 2020-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_item_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_bid',
            field=models.IntegerField(default=1),
        ),
    ]
