# Generated by Django 3.0.8 on 2020-08-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_min_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_bid',
            field=models.FloatField(default=1.0),
        ),
    ]
