# Generated by Django 3.0.8 on 2020-08-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200801_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='ammount',
            field=models.FloatField(),
        ),
    ]
