# Generated by Django 3.0.8 on 2020-08-02 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 11, 10, 20, 928958, tzinfo=utc)),
        ),
    ]
