# Generated by Django 3.0.8 on 2020-08-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
    ]
