# Generated by Django 3.0.8 on 2020-08-13 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Item',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auctions.Item'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bid',
        ),
    ]
